# Generated by Django 3.2.5 on 2021-07-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210707_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
